---
title: "R Notebook"
output: html_notebook
---

Biomass assay of fungi P. citrinum CCH_F37_B for ambient and temperature 

packages and dependencies 
```{r}
#install.packages("ggplot2")
library(ggplot2)
#install.packages("tidyverse")
library(tidyverse)
#install.packages("ggpubr")
library(ggpubr)
#install.packages("lsmeans")
library(lsmeans)
#install.packages("emmeans")
library(emmeans)
library(lme4)
```

Color blind palette
```{r}
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
```

Loading data set
```{r}
biomass_assay <- read.csv("/Users/lau/Desktop/AU_research/Old_Rotation/Jan2022/Biomas_assay/Biomas_assay2023.csv", na.strings = "na")
```


First let's see do a linear model to see any significance btw growth and salt concentration
```{r}
lm.biomass <- lm(Final_weight.flask~ Treatment, data = biomass_assay)
#plot(lm)
summary(lm.biomass)
anova(lm.biomass)
```
graph
```{r}
ggplot(biomass_assay, aes(x = Label, y = Final_weight.flask, fill = Treatment)) +								
  stat_summary(fun.y=mean,geom="bar", position = "dodge") +								
  stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.5, position = "dodge") +								
  ylab("Biomass") +								
  xlab("Penicillium citrinum")+								
  #scale_color_manual(values=cbbPalette) +								
  #stat_compare_means(method = "t.test") +								
  theme_classic()	+						
  coord_flip()								
#facet_wrap(~Label, scales = "free")		
```


